- name: Download iOS SDK
  if: steps.SDK.outputs.cache-hit != 'true'
  run: |
    git clone --quiet -n --depth=1 --filter=tree:0 https://$GH_TOKEN@github.com/arichorn/sdks/
    cd sdks
    git sparse-checkout set --no-cone iPhoneOS16.2.sdk
    git checkout
    mv *.sdk $THEOS/sdks
  env:
    THEOS: ${{ github.workspace }}/theos
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
